defi-wonderland/hardhat-account-abstraction

- src/gasless-provider.ts
> feat: reusing sender address

- .github/workflows/build.yml
- .github/workflows/lint.yml
- yarn.lock
> chore: add workflows

- src/gasless-provider.ts
- src/index.ts
- src/type-extensions.ts
- test/fixture-projects/hardhat-project/hardhat.config.ts
- test/project.test.ts
- yarn.lock
> feat: add entry point as optional parameter

- src/constants.ts
- src/gasless-provider.ts
- src/index.ts
- src/type-extensions.ts
- test/fixture-projects/hardhat-project/hardhat.config.ts
- test/project.test.ts
> chore: getting entry point dynamically

- src/gasless-provider.ts
- src/paymaster.ts
- src/paymasters/StackUpPaymaster.ts
- src/paymasters/index.ts
- src/types.ts
> feat: add stackup paymaster

- README.md
> docs: add license in readme

- src/index.ts
- src/paymaster.ts
- src/paymasters/AlchemyPaymaster.ts
- src/paymasters/BasePaymaster.ts
- src/paymasters/index.ts
- src/type-extensions.ts
- src/types.ts
- src/utils.ts
> feat: add alchemy paymaster

- src/gasless-provider.ts
- src/paymasters/BasePaymaster.ts
- src/paymasters/Paymaster.ts
- src/paymasters/PimlicoPaymaster.ts
- src/paymasters/StackUpPaymaster.ts
- src/utils.ts
> refactor: gasless provider unused branch and extra function

- src/paymasters/AlchemyPaymaster.ts
- src/paymasters/BasePaymaster.ts
- src/paymasters/Paymaster.ts
- src/paymasters/PimlicoPaymaster.ts
- src/paymasters/StackUpPaymaster.ts
- src/utils.ts
> feat: implement json rpc provider

- src/paymaster.ts
- src/paymasters/PimlicoPaymaster.ts
> feat: optional policy id for pimlico

- CONTRIBUTORS.md
- LICENSE
- README.md
> docs: adding paymaster tutorial

- .eslintrc.json
- README.md
- src/gasless-provider.ts
- src/index.ts
- src/paymasters/AlchemyPaymaster.ts
- src/paymasters/Paymaster.ts
- src/paymasters/PimlicoPaymaster.ts
- src/paymasters/StackUpPaymaster.ts
- src/type-extensions.ts
> feat: add optional param to use an already deployed smart account

- src/gasless-provider.ts
- src/index.ts
- test/gasless-provider.test.ts
> feat: add check for chainId

- test/gasless-provider.test.ts
- test/helpers.ts
- test/paymasters/PimlicoPaymaster.test.ts
> test: pimlico paymaster

- test/paymasters/StackUpPaymaster.test.ts
> test: add tests for stackUp

- test/paymasters/BasePaymaster.test.ts
> test: base paymaster

- src/gasless-provider.ts
- src/utils.ts
> chore: use sender address as salt

- README.md
- src/gasless-provider.ts
- src/utils.ts
> feat: create getSmartAccountData function

- src/gasless-provider.ts
- src/types.ts
> fix: non-zero value transactions

- src/gasless-provider.ts
> feat: log the tx hash

- test/integration/transactions.test.ts
> test: move duplicated code to before

- .github/workflows/release.yml
- .gitignore
- CONTRIBUTORS.md
- README.md
- package.json
- src/gasless-provider.ts
- src/index.ts
- src/type-extensions.ts
- test/fixture-projects/integration/hardhat.config.ts
- test/fixture-projects/unit/hardhat.config.ts
- test/integration/deployment.test.ts
- test/integration/transactions.test.ts
- test/unit/project.test.ts
> docs: change name to hardhat-account-abstraction

- README.md
- Cleans up the docs for release
> docs: typos and smart account deployment explanation

- README.md
> docs: quick start
